---

- hosts: all
  become: yes
  tasks:
  -  name: Install zabbix-agent rpm from a remote repo on RedHat Family
     ansible.builtin.yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm
        state: present
     when:
        ansible_os_family == "RedHat"
  -  name: Install zabbix-agent on RedHat Family
     ansible.builtin.yum:
        name: zabbix-agent
        state: present
     when:
        ansible_os_family == "RedHat"
     notify:
        zabbix-agent systemd
  -  name: Install zabbix-agent from a remote repo on Ubuntu
     ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb
     when:
        ansible_os_family == "Debian"
  -  name: Install zabbix-agent on Ubuntu
     ansible.builtin.apt:
        name: zabbix-agent
        state: present
     when:
        ansible_os_family == "Debian"
     notify:
        zabbix-agent systemd
  -  name: Remove zabbix config file
     file:
        path: "/etc/zabbix/zabbix_agentd.conf"
        state: absent
  -  name: Create new zabbix config file from template
     template:
        src: "/etc/ansible/common/files/zabbix_agentd.conf"
        dest: "/etc/zabbix/zabbix_agentd.conf"
  handlers:
  -  name: zabbix-agent systemd
     systemd:
        name: zabbix-agent.service
        enabled: yes
        state: started
